/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appIventario;
import java.util.logging.Level;
import java.util.logging.Logger;
import ormlite.Ormlite;
import ormlite.Producto;
    
/**
 *
 * @author skabe
 */
public class AgregarElemento extends javax.swing.JFrame {

    /**
     * Creates new form AgregarElemento
     */
    public AgregarElemento() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoProd = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        cod = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        des = new javax.swing.JTextField();
        sto = new javax.swing.JTextField();
        pre = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codigoProd.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        codigoProd.setForeground(new java.awt.Color(0, 0, 255));
        codigoProd.setText("Codigo del Producto:");
        getContentPane().add(codigoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        descripcion.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        descripcion.setForeground(new java.awt.Color(0, 0, 255));
        descripcion.setText("Descripción:");
        getContentPane().add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        nombre.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 255));
        nombre.setText("Nombre:");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        stock.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        stock.setForeground(new java.awt.Color(51, 255, 51));
        stock.setText("Stock:");
        getContentPane().add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        precio.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        precio.setForeground(new java.awt.Color(51, 255, 51));
        precio.setText("Precio:");
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        agregar.setBackground(new java.awt.Color(0, 255, 0));
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 190, -1));
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 190, -1));
        getContentPane().add(des, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 190, -1));
        getContentPane().add(sto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 190, -1));
        getContentPane().add(pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 190, -1));

        salir.setBackground(new java.awt.Color(255, 0, 51));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 773, 229));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        Producto auxiliar= new Producto(cod.getText(), nom.getText(), des.getText(), sto.getText(), pre.getText());
        try {
            Ormlite.insertar(auxiliar);
        } catch (Exception ex) {
            Logger.getLogger(AgregarElemento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_agregarActionPerformed

    public static void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarElemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarElemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarElemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarElemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AgregarElemento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField cod;
    private javax.swing.JLabel codigoProd;
    private javax.swing.JTextField des;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField nom;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField pre;
    private javax.swing.JLabel precio;
    private javax.swing.JButton salir;
    private javax.swing.JTextField sto;
    private javax.swing.JLabel stock;
    // End of variables declaration//GEN-END:variables
}
