/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appIventario;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import ormlite.Ormlite;
import ormlite.Producto;

/**
 *
 * @author skabe
 */
public class JFrameInvetarioChido extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInvetarioChido
     */
    ArrayList<Producto> lista;
    public JFrameInvetarioChido() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actualizar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        busqueda = new javax.swing.JTextField();
        actualizarUno = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        vaciarTabla = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizar.setBackground(new java.awt.Color(102, 255, 102));
        actualizar.setText("Actualizar Tabla Actual");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, -1, -1));

        buscar.setBackground(new java.awt.Color(102, 153, 255));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, -1, -1));

        agregar.setBackground(new java.awt.Color(51, 51, 255));
        agregar.setText("Agregar Elemento");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        getContentPane().add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 200, -1));

        actualizarUno.setBackground(new java.awt.Color(0, 255, 0));
        actualizarUno.setText("Actualizar un elemento");
        actualizarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarUnoActionPerformed(evt);
            }
        });
        getContentPane().add(actualizarUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        eliminar.setBackground(new java.awt.Color(255, 0, 51));
        eliminar.setText("Eliminar Elemento");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, -1, -1));

        vaciarTabla.setBackground(new java.awt.Color(255, 0, 51));
        vaciarTabla.setText("Vaciar Tabla");
        vaciarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciarTablaActionPerformed(evt);
            }
        });
        getContentPane().add(vaciarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        resultado.setEditable(false);
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 470, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Resultado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Descripcion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Introdusca el codigo de producto a buscar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        desc.setEditable(false);
        getContentPane().add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 350, 60));

        salir.setBackground(new java.awt.Color(255, 0, 0));
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "codigoProducto", "nombre", "descripcion", "stock", "precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, 250));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1021, 633));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        AgregarElemento.iniciar();
    }//GEN-LAST:event_agregarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try {
            Producto auxiliar= Ormlite.consutarPorCodigo(busqueda.getText());
            resultado.setText("Codigo: "+auxiliar.getCodigoProducto()+" Nombre: "+
                    auxiliar.getNombre()+" Stock: "+auxiliar.getStock()+" Precio: $"+auxiliar.getPrecio());
            desc.setText(auxiliar.getDescricion());
        } catch (Exception ex) {
            Logger.getLogger(JFrameInvetarioChido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        try {
            lista= Ormlite.consutarTodo();
            String matriz [][]= new String[lista.size()][5];
            for(int i=0; i<lista.size();i++){
                matriz[i][0]=lista.get(i).getCodigoProducto();
                matriz[i][1]=lista.get(i).getNombre();
                matriz[i][2]=lista.get(i).getDescricion();
                matriz[i][3]=lista.get(i).getStock();
                matriz[i][4]=lista.get(i).getPrecio();
            }
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "codigoProducto", "nombre", "descripcion", "stock", "precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };
            
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        } catch (Exception ex) {
            Logger.getLogger(JFrameInvetarioChido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void actualizarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarUnoActionPerformed
        ActualizarElemento.iniciar();
    }//GEN-LAST:event_actualizarUnoActionPerformed

    private void vaciarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciarTablaActionPerformed
        try {
            Ormlite.eliminarTabla();
        } catch (Exception ex) {
            Logger.getLogger(JFrameInvetarioChido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vaciarTablaActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        try {
            Ormlite.eliminarUno(busqueda.getText());
        } catch (Exception ex) {
            Logger.getLogger(JFrameInvetarioChido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    public static void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInvetarioChido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInvetarioChido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInvetarioChido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInvetarioChido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInvetarioChido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton actualizarUno;
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField busqueda;
    private javax.swing.JTextField desc;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField resultado;
    private javax.swing.JButton salir;
    private javax.swing.JButton vaciarTabla;
    // End of variables declaration//GEN-END:variables
}
